//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by PictureShow.rc
//
#define IDR_MAINFRAME                   11
#define IDI_BMP                         12
#define IDI_DIB                         13
#define IDI_EMF                         14
#define IDI_GIF                         15
#define IDI_ICO                         16
#define IDI_JPG                         17
#define IDI_WMF                         18
#define IDD_ABOUTBOX                    100
#define IDD_DIALOG_STATUS_COORD         101
#define IDD_DRAWINGSTYLE_CONFIG         102
#define IDR_DEFAULT                     130
#define IDD_ASSOCIATIONS                131
#define IDR_FULLSCREEN                  145
#define IDR_MAINFRAME_EDITED            146
#define IDC_CURSOR_PEN                  153
#define IDC_SETUP_TEXT_COLOR_SEL        590
#define IDC_SETUP_TEXT_COLOR            591
#define IDC_SETUP_TEXT_BACKCOLOR        597
#define IDC_SETUP_TEXT_BACKCOLOR_SEL    598
#define IDC_SETUP_CAMDIREC_COLOR        599
#define IDC_SETUP_CAMDIREC_COLOR_SEL    600
#define IDC_SETUP_REFPOINT_COLOR        601
#define IDC_SETUP_REFPOINT_COLOR_SEL    602
#define IDC_SETUP_TARGETPOINT_COLOR     603
#define IDC_SETUP_TARGETPOINT_COLOR_SEL 604
#define IDC_SETUP_LINE_COLOR            605
#define IDC_SETUP_LINE_COLOR_SEL        606
#define IDC_CHECK_JPG                   1000
#define IDC_BUTTON_ASSOCIATE            1001
#define IDC_CHECK_BMP                   1002
#define IDC_CHECK_DIB                   1003
#define IDC_CHECK_EMF                   1004
#define IDC_COMBO_CAMDIREC_SYMBOL       1004
#define IDC_CHECK_GIF                   1005
#define IDC_COMBO_REFPOINT_SYMBOL       1005
#define IDC_CHECK_ICO                   1006
#define IDC_COMBO_TARGETPOINT_SYMBOL    1006
#define IDC_CHECK_WMF                   1007
#define IDC_EDIT_CAMDIREC_OPACITY       1007
#define IDC_EDIT_REFPOINT_LINEWIDTH     1008
#define IDC_CHECK_ALL                   1009
#define IDC_EDIT_TARGETPOINT_LINEWIDTH  1009
#define IDC_BUTTON_HIDE                 1010
#define IDC_EDIT_ABOUT                  1011
#define IDC_COMBO_LINE_SYMBOL           1011
#define IDC_BUTTON_CLEAR                1012
#define IDC_EDIT_REFPOINT_OPACITY       1012
#define IDC_STATIC_DMS                  1013
#define IDC_EDIT_LINE_OPACITY           1013
#define IDC_STATIC_MGRS                 1014
#define IDC_EDIT_CAMDIREC_SYMBOLSIZE    1014
#define IDC_STATIC_VIEW_PIXEL           1015
#define IDC_EDIT_REFPOINT_SYMBOLSIZE    1015
#define IDC_STATIC_ORGIMG_PIXEL         1016
#define IDC_EDIT_TARGETPOINT_SYMBOLSIZE 1016
#define IDC_STATIC_MAGNIFY              1017
#define IDC_STATIC_MAGNIFICATION        1017
#define IDC_CHECK_REFPOINT_NUM          1017
#define IDC_STATIC_DMS2                 1018
#define IDC_STATIC_TM                   1018
#define IDC_EDIT_LINE_LINEWIDTH         1018
#define IDC_STATIC_CAMPOS               1019
#define IDC_BUTTON_APPLY                1019
#define IDC_STATIC_TARGETINFO           1020
#define IDC_EDIT_LINE_OPACITY2          1020
#define IDC_EDIT_TARGETPOINT_OPACITY    1020
#define IDC_STATIC_CAMPOS2              1021
#define IDC_STATIC_CAMINFO              1021
#define IDC_STATIC_TARGETINFO2          1022
#define IDC_STATIC_TARGETINFO_MGRS      1022
#define IDC_STATIC_MOUSE_PANTILT        1023
#define IDC_STATIC_CAMPOS_MGRS          1024
#define IDC_STATIC_1                    1025
#define IDC_STATIC_2                    1026
#define IDC_STATIC_3                    1027
#define IDC_CHECK_DOCKING_TOP           1028
#define IDC_RADIO_CH1                   1029
#define IDC_RADIO_CH2                   1030
#define IDC_RADIO_CH3                   1031
#define IDC_RADIO_CH4                   1032
#define IDC_RADIO_CH5                   1033
#define ID_OPTIONS_FITTOSCREEN          32771
#define ID_BUTTON_DIMINISH              32775
#define ID_BUTTON_MAGNIFY               32776
#define ID_OPTIONS_ASSOCIATEFILEEXTENTIONS 32777
#define ID_BUTTON_FITTOSCREEN           32778
#define ID_BUTTON_PREV                  32785
#define ID_BUTTON_NEXT                  32786
#define ID_OPTIONS_FULLSCREEN           32787
#define ID_BUTTON_FULLSCREEN            32805
#define ID_BUTTON_FULLSCREEN_FLOAT      32808
#define ID_HELP_WEBPAGE                 32809
#define ID_HELP_HOMEPAGE                32810
#define ID_TEST_FITBORDERS              32811
#define ID_OPTIONS_FITBORDERSTOPICTURE  32812
#define ID_OPTIONS_NEXTPICTURE          32813
#define ID_OPTIONS_                     32814
#define ID_OPTIONS_PREVIOUSPICTURE      32814
#define ID_BUTTON_MAP1                  32815
#define ID_BUTTON_MAP2                  32816
#define ID_BUTTON32820                  32820
#define ID_BUTTON32821                  32821
#define ID_BUTTON_MAP_OPEN              32824
#define ID_BUTTON_PEN                   32835
#define ID_LINE_SAVE                    32839
#define ID_BUTTON_DRAWING_LOAD          32842
#define ID_BUTTON_STYLE_SETUP           32843
#define ID_LINE_UNDO                    32844
#define ID_BUTTON_NEW_DRAWING           32848
#define ID_BUTTON32849                  32849
#define ID_HIDDEN_MENU                  32850
#define ID_ID_HIDDEN_MENU               32850
#define ID_RULER_SHOW                   32852
#define ID_INDICATOR_INFO               59142

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_3D_CONTROLS                     1
#define _APS_NEXT_RESOURCE_VALUE        157
#define _APS_NEXT_COMMAND_VALUE         32854
#define _APS_NEXT_CONTROL_VALUE         1030
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
