// Machine generated IDispatch wrapper class(es) created by Microsoft Visual C++

// NOTE: Do not modify the contents of this file.  If this class is regenerated by
//  Microsoft Visual C++, your modifications will be overwritten.


#include "stdafx.h"
#include "tvsdecodecontrol.h"

/////////////////////////////////////////////////////////////////////////////
// CTVSDecodeControl

IMPLEMENT_DYNCREATE(CTVSDecodeControl, CWnd)

/////////////////////////////////////////////////////////////////////////////
// CTVSDecodeControl properties

/////////////////////////////////////////////////////////////////////////////
// CTVSDecodeControl operations

LPDISPATCH CTVSDecodeControl::GetDisplay()
{
	LPDISPATCH result;
	InvokeHelper(0x1, DISPATCH_METHOD, VT_DISPATCH, (void*)&result, NULL);
	return result;
}

long CTVSDecodeControl::Open(BOOL bDisplay, BOOL bEvent, LPUNKNOWN pCallback)
{
	long result;
	static BYTE parms[] =
		VTS_BOOL VTS_BOOL VTS_UNKNOWN;
	InvokeHelper(0x2, DISPATCH_METHOD, VT_I4, (void*)&result, parms,
		bDisplay, bEvent, pCallback);
	return result;
}

BOOL CTVSDecodeControl::Close(long lChID)
{
	BOOL result;
	static BYTE parms[] =
		VTS_I4;
	InvokeHelper(0x3, DISPATCH_METHOD, VT_BOOL, (void*)&result, parms,
		lChID);
	return result;
}

BOOL CTVSDecodeControl::PutData(long lChID, const VARIANT& vData)
{
	BOOL result;
	static BYTE parms[] =
		VTS_I4 VTS_VARIANT;
	InvokeHelper(0x4, DISPATCH_METHOD, VT_BOOL, (void*)&result, parms,
		lChID, &vData);
	return result;
}

BOOL CTVSDecodeControl::StartDecoding(long lChID)
{
	BOOL result;
	static BYTE parms[] =
		VTS_I4;
	InvokeHelper(0x5, DISPATCH_METHOD, VT_BOOL, (void*)&result, parms,
		lChID);
	return result;
}

BOOL CTVSDecodeControl::StopDecoding(long lChID)
{
	BOOL result;
	static BYTE parms[] =
		VTS_I4;
	InvokeHelper(0x6, DISPATCH_METHOD, VT_BOOL, (void*)&result, parms,
		lChID);
	return result;
}

BOOL CTVSDecodeControl::SetOutputFormat(long lChID, long eFormat)
{
	BOOL result;
	static BYTE parms[] =
		VTS_I4 VTS_I4;
	InvokeHelper(0x7, DISPATCH_METHOD, VT_BOOL, (void*)&result, parms,
		lChID, eFormat);
	return result;
}


