#if !defined(AFX_TVSDISPLAY_H__E3924B7A_4B7A_47E1_8539_F817D9D8D150__INCLUDED_)
#define AFX_TVSDISPLAY_H__E3924B7A_4B7A_47E1_8539_F817D9D8D150__INCLUDED_

#if _MSC_VER > 1000
#pragma once
#endif // _MSC_VER > 1000
// Machine generated IDispatch wrapper class(es) created by Microsoft Visual C++

// NOTE: Do not modify the contents of this file.  If this class is regenerated by
//  Microsoft Visual C++, your modifications will be overwritten.

/////////////////////////////////////////////////////////////////////////////
// CTVSDisplay wrapper class

class CTVSDisplay : public COleDispatchDriver
{
public:
	CTVSDisplay() {}		// Calls COleDispatchDriver default constructor
	CTVSDisplay(LPDISPATCH pDispatch) : COleDispatchDriver(pDispatch) {}
	CTVSDisplay(const CTVSDisplay& dispatchSrc) : COleDispatchDriver(dispatchSrc) {}

// Attributes
public:

// Operations
public:
	short GetMonitorCount();
	long GetLayoutMode(short nMonitor);
	void SetLayoutMode(short nMonitor, long nNewValue);
	long GetDUCount(short nMonitor);
	void SetDUCount(short nMonitor, long nNewValue);
	long GetMapChannel(short nMonitor, long nDU);
	void SetMapChannel(short nMonitor, long nDU, long nNewValue);
	BOOL SetDURect(short nMonitor, long nDU, short nLeft, short nTop, short nRight, short nBottom);
	BOOL GetDURect(short nMonitor, long nDU, short* pnLeft, short* pnTop, short* pnRight, short* pnBottom);
	BOOL GetShowToolbar(long lChID);
	void SetShowToolbar(long lChID, BOOL bNewValue);
	long GetToolbarConfig(long lChID);
	void SetToolbarConfig(long lChID, long nNewValue);
	long AddOsdArea(long lChID, short nLeft, short nTop, short nRight, short nBottom, short nType);
	void RemoveOsdArea(long lOSDID);
	void UpdateOsdArea(long lOSDID, const VARIANT& vData);
	short GetOsdType(long lOSDID);
	long GetOsdForeColor(long lOSDID);
	void SetOsdForeColor(long lOSDID, long nNewValue);
	long GetOsdBackColor(long lOSDID);
	void SetOsdBackColor(long lOSDID, long nNewValue);
	BOOL GetOsdTransparency(long lOSDID);
	void SetOsdTransparency(long lOSDID, BOOL bNewValue);
	CString GetOsdFontName(long lOSDID);
	void SetOsdFontName(long lOSDID, LPCTSTR lpszNewValue);
	short GetOsdFontSize(long lOSDID);
	void SetOsdFontSize(long lOSDID, short nNewValue);
	void SetDigitalZoom(long lChID, long lZoom, long xStart, long yStart);
	void GetDigitalZoom(long lChID, long* lZoom, long* xStart, long* yStart);
	HRESULT SetChannelFlip(long lChID, long lMode);
	HRESULT GetChannelFlip(long lChID, long* lMode);

};

//{{AFX_INSERT_LOCATION}}
// Microsoft Visual C++ will insert additional declarations immediately before the previous line.

#endif // !defined(AFX_TVSDISPLAY_H__E3924B7A_4B7A_47E1_8539_F817D9D8D150__INCLUDED_)
