#if !defined(AFX_TVSDECODECONTROL_H__6A29F790_2108_4048_BF74_827553E39389__INCLUDED_)
#define AFX_TVSDECODECONTROL_H__6A29F790_2108_4048_BF74_827553E39389__INCLUDED_

#if _MSC_VER > 1000
#pragma once
#endif // _MSC_VER > 1000
// Machine generated IDispatch wrapper class(es) created by Microsoft Visual C++

// NOTE: Do not modify the contents of this file.  If this class is regenerated by
//  Microsoft Visual C++, your modifications will be overwritten.

/////////////////////////////////////////////////////////////////////////////
// CTVSDecodeControl wrapper class

class CTVSDecodeControl : public CWnd
{
protected:
	DECLARE_DYNCREATE(CTVSDecodeControl)
public:
	CLSID const& GetClsid()
	{
		static CLSID const clsid
			= { 0xca1b836a, 0x156f, 0x40bd, { 0xa2, 0xf5, 0xf7, 0xaa, 0xbe, 0xfa, 0xd6, 0x92 } };
		return clsid;
	}
	virtual BOOL Create(LPCTSTR lpszClassName,
		LPCTSTR lpszWindowName, DWORD dwStyle,
		const RECT& rect,
		CWnd* pParentWnd, UINT nID,
		CCreateContext* pContext = NULL)
	{ return CreateControl(GetClsid(), lpszWindowName, dwStyle, rect, pParentWnd, nID); }

    BOOL Create(LPCTSTR lpszWindowName, DWORD dwStyle,
		const RECT& rect, CWnd* pParentWnd, UINT nID,
		CFile* pPersist = NULL, BOOL bStorage = FALSE,
		BSTR bstrLicKey = NULL)
	{ return CreateControl(GetClsid(), lpszWindowName, dwStyle, rect, pParentWnd, nID,
		pPersist, bStorage, bstrLicKey); }

// Attributes
public:

// Operations
public:
	LPDISPATCH GetDisplay();
	long Open(BOOL bDisplay, BOOL bEvent, LPUNKNOWN pCallback);
	BOOL Close(long lChID);
	BOOL PutData(long lChID, const VARIANT& vData);
	BOOL StartDecoding(long lChID);
	BOOL StopDecoding(long lChID);
	BOOL SetOutputFormat(long lChID, long eFormat);
};

//{{AFX_INSERT_LOCATION}}
// Microsoft Visual C++ will insert additional declarations immediately before the previous line.

#endif // !defined(AFX_TVSDECODECONTROL_H__6A29F790_2108_4048_BF74_827553E39389__INCLUDED_)
